version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: dev-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: dev-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped